# -*- coding: utf-8 -*-
"""roman_converter_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z2E5DAQZTeYBrOtFIxn0FiJFnyQqUhzU
"""

# Conversion Functions

def roman_to_int(roman):
    roman_values = {
        "I": 1, "V": 5, "X": 10, "L": 50,
        "C": 100, "D": 500, "M": 1000
    }

    total = 0
    prev_value = 0

    for char in reversed(roman.upper()):
        if char not in roman_values:
            return "Invalid Roman numeral!"
        value = roman_values[char]
        if value < prev_value:
            total -= value
        else:
            total += value
        prev_value = value
    return total

def int_to_roman(num):
    if not (0 < num < 4000):
        return "Enter a number between 1 and 3999"

    value_map = [
        (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"),
        (100, "C"), (90, "XC"), (50, "L"), (40, "XL"),
        (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I")
    ]

    roman = ""
    for value, symbol in value_map:
        while num >= value:
            roman += symbol
            num -= value
    return roman


# Streamlit App Interface

st.set_page_config(page_title="Roman ↔ Integer Converter", page_icon="🏛️", layout="centered")

st.title("🏛️ Roman ↔ Integer Converter")

st.write("Convert between **Roman numerals** and **integers** easily!")

# Choose conversion direction
mode = st.radio("Select conversion direction:", ["Roman → Integer", "Integer → Roman"])

st.divider()

# --- Roman → Integer ---
if mode == "Roman → Integer":
    roman_input = st.text_input("Enter a Roman numeral:", placeholder="e.g. MCMXCIV")
    if roman_input:
        result = roman_to_int(roman_input)
        st.success(f"✅ Integer value: **{result}**")

# --- Integer → Roman ---
else:
    number_input = st.number_input("Enter an integer (1–3999):", min_value=1, max_value=3999, step=1)
    if number_input:
        result = int_to_roman(number_input)
        st.success(f"✅ Roman numeral: **{result}**")

st.divider()
st.caption("Made with ❤️ by Santanu — Chemistry meets Python 🧪")
